name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Compile Java code
      run: javac -d bin src/*.java 
    - name: Run Unit Tests
      run: java -cp bin org.junit.runner.JUnitCore GradeCalculatorTest  