name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Download JUnit 5 and Dependencies
      run: |
        mkdir -p libs
        curl -L -o libs/junit-jupiter-api-5.7.0.jar https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.7.0/junit-jupiter-api-5.7.0.jar
        curl -L -o libs/opentest4j-1.2.0.jar https://repo1.maven.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
        curl -L -o libs/junit-platform-commons-1.7.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar
        curl -L -o libs/apiguardian-api-1.1.0.jar https://repo1.maven.org/maven2/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar
        curl -L -o libs/junit-platform-console-standalone-1.7.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar

    - name: Check Downloads
      run: ls -lh libs  

    - name: Compile Java code
      run: javac -d bin --module-path libs -cp "libs/*" src/*.java

    - name: Verify Compiled Files
      run: ls -lh bin  

    - name: Run Unit Tests
      run: java -jar libs/junit-platform-console-standalone-1.7.0.jar --class-path bin --select-class GradeCalculatorTest
